apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: todo
spec:
  replicas: 1
  template:
    metadata:
      name: todo
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: todo-example:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: todo
