apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-deployment
spec:
  selector:
    matchLabels:
      app: to-do-app
  replicas: 1
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
        - name: to-do-app
          image: noytim/to-do-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1 # Kubernetes API Version
kind: Service # Kubernetes resource we are creating
metadata: # Metadata of the resource we are creating
  name: to-do-service
spec:
  selector:
    app: to-do-app
  ports:
    - port: 9000 # the port that the service is running on in the cluster
      targetPort: 8080 # the port exposed to the service
  type: NodePort # type of the service
